#!/usr/bin/rake -f
# -*- coding: utf-8 -*-
#
# Author:: lnznt
# Copyright:: (C) 2011 lnznt.
# License:: Ruby's
#
dsa_key      = "dsa_key.pem"
dsa_keyparam = "dsa_keyparam.pem"
rsa_key      = "rsa_key.pem"

task :default => [dsa_key, rsa_key]

file dsa_key => dsa_keyparam do
  sh "openssl gendsa #{dsa_keyparam} > #{dsa_key}"
end

file dsa_keyparam do
  sh "openssl dsaparam 1024 > #{dsa_keyparam}"
end

file rsa_key do
  sh "openssl genrsa 1024 > #{rsa_key}"
end
